_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: ""
  RESNETS:
    DEPTH: 14
    NORM: "GN"
    STRIDE_IN_1X1: False
  FPN:
    NORM: "GN"
  BACKBONE:
    FREEZE_AT: 0
SOLVER:
  # 3x schedule
  STEPS: (210000, 250000)
  MAX_ITER: 270000