_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "ProposalNetwork"
  WEIGHTS: "https://dl.fbaipublicfiles.com/detectron2/COCO-Detection/rpn_R_50_FPN_1x/137258492/model_final_02ce48.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  RPN:
    POST_NMS_TOPK_TEST: 2000
