_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    FC_DIM_LIST: [2048, 1024]
    NUM_CONV: 4
    CONV_DIM_LIST: [512, 256, 128, 64]
    POOLER_RESOLUTION: 14
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
